- name: yum install for Apache Web Server
  yum: name=httpd state=latest
  with_items:
    - httpd

- name: Change the httpd.conf to template file ( Apache 2.2 )
  copy: src=httpd22.conf dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6

- name: Change the httpd.conf to template file ( Apache 2.4 )
  copy: src=httpd24.conf dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 7
