- name: (Initialize) SELinux desabled initialize
  yum: name=libselinux-python state=latest

- name: (Initialize) SELinux desabled
  selinux: state=disabled

#- name: (Initialize) Firewalld stopped ( CentOS 7 )
#  service: name=firewalld state=stopped enabled=no
#  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 7

- name: (Initialize) iptables stopped ( CentOS 6 )
  service: name=iptables state=stopped enabled=no
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6

- name: (Initialize) ip6tables stopped ( CentOS 6 )
  service: name=ip6tables state=stopped enabled=no
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6

- name: (Initialize) Timezone setting
  file: src="/usr/share/zoneinfo/Asia/Tokyo" dest="/etc/localtime" state=link force=yes

- name: (Initialize) Timezone setting ( CentOS 6 )
  replace: dest="/etc/sysconfig/clock" regexp='^ZONE=\"UTC\"' replace='ZONE="Asia/Tokyo"'
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6

- name: (Initialize) Locale setting ( CentOS 7 )
  replace: dest="/etc/locale.conf" regexp='^LANG=en_US\.UTF-8' replace='LANG=ja_JP.UTF-8'
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 7

- name: (Initialize) Locale setting ( CentOS 6 )
  replace: dest="/etc/sysconfig/i18n" regexp='^LANG=en_US\.UTF-8' replace='LANG=ja_JP.UTF-8'
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6

- name: (Initialize) motd.sh setting
  copy: src=motd.sh dest=/etc/profile.d/ owner=root group=root mode=0755

- name: (Initialize) history file setting 1
  lineinfile:
    dest: /etc/bashrc
    line: HISTSIZE=10000

- name: (Initialize) history file setting 2
  lineinfile:
    dest: /etc/bashrc
    line: HISTTIMEFORMAT='%Y/%m/%d %H:%M:%S '
